"use client";

import { useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { ChevronDown, ChevronRight, MoreVertical, Sparkles } from "lucide-react";
import {
  markNonDocumentNeedAccepted,
  reopenNonDocumentNeed,
  updateClientNeed,
  deleteClientNeedFromDeal,
  autoGenerateClientNeedsForProduct,
  putClientNeedOnHold,
  resumeClientNeedFromHold,
} from "@/server/actions/client-needs";
import {
  attachDocumentToClientNeed,
  approveClientNeedDocuments,
  rejectClientNeedDocuments,
} from "@/server/actions/client-need-documents";
import {
  reviewClientNeedDocuments,
  reviewAllClientNeedDocumentsForDeal,
} from "@/server/ai/client-need-document-review";
import {
  previewClientNeedsUpdateEmail,
  sendClientNeedsUpdateEmail,
} from "@/server/actions/client-needs-email";
import { updateClientNeedsReminderSettings, getOrCreateBorrowerUploadLink } from "@/server/actions/deals";
import { getCustomFormDefinition } from "@/lib/custom-need-forms/registry";
import { CLIENT_NEEDS_REMINDER_INTERVAL_HOURS } from "@/lib/client-needs-reminders";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { CopyClientNeedsButton } from "@/components/deals/copy-client-needs-button";
import { AddClientNeedToDealDialog, type DealCatalogItem } from "@/components/deals/add-client-need-to-deal-dialog";
import {
  ClientNeedDocumentReviewDialog,
  type ReviewableDocument,
} from "@/components/deals/client-need-document-review-dialog";
import { RecipientLine } from "@/components/emails/recipient-line";
import { SignaturePreview } from "@/components/emails/signature-preview";
import { HtmlBodyEditor } from "@/components/emails/html-body-editor";
import type { RecipientCandidate } from "@/lib/email-recipients";

export interface ClientNeedAnswer {
  id: string;
  questionText: string;
  answerText: string | null;
}

export interface ClientNeed {
  id: string;
  itemName: string;
  description: string | null;
  status: "not_sent" | "awaiting_docs" | "review_needed" | "accepted";
  needType: "document_upload" | "esign" | "questionnaire" | "link" | "pandadoc_form" | "custom_form";
  minFiles: number;
  sentAt: Date | null;
  onHoldAt: Date | null;
  onHoldNote: string | null;
  linkUrl: string | null;
  templateFileName: string | null;
  pandadocDocumentId: string | null;
  customFormKey: string | null;
  customFormData: Record<string, string> | null;
  documents: ReviewableDocument[];
  answers: ClientNeedAnswer[];
}

// Splits the list into two toggleable tabs — signature-oriented needs
// (traditional e-sign vendor tasks and PandaDoc forms, which fill AND sign)
// versus everything else the borrower just uploads, answers, or clicks
// through. Keeps a long checklist from turning into one undifferentiated
// wall of cards.
const ESIGN_NEED_TYPES = new Set(["esign", "pandadoc_form"]);

const STATUS_LABEL: Record<ClientNeed["status"], string> = {
  not_sent: "Not Sent",
  awaiting_docs: "Awaiting Docs",
  review_needed: "Review Needed",
  accepted: "Accepted",
};

const STATUS_VARIANT: Record<ClientNeed["status"], "destructive" | "secondary" | "warning" | "success"> = {
  not_sent: "destructive",
  awaiting_docs: "secondary",
  review_needed: "warning",
  accepted: "success",
};

function CopyUploadLinkItem({ dealId }: { dealId: string }) {
  async function handleClick() {
    try {
      const link = await getOrCreateBorrowerUploadLink(dealId);
      await navigator.clipboard.writeText(link);
      toast.success("Upload link copied");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Couldn't get the upload link.");
    }
  }

  return <DropdownMenuItem onClick={handleClick}>Copy upload link</DropdownMenuItem>;
}

// Client-need sets are scoped to lender + loan category (a specific
// product), not the loan category alone — different lenders genuinely want
// different things for the same loan type (one wants a 1003, another has
// their own application). So this asks which lender's product to pull the
// checklist from, defaulting to the deal's own product once one is chosen.
function AutoGenerateDialog({
  dealId,
  products,
  currentProductId,
}: {
  dealId: string;
  products: { id: string; label: string }[];
  currentProductId: string | null;
}) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [productId, setProductId] = useState(currentProductId ?? "");
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  function handleOpenChange(next: boolean) {
    setOpen(next);
    if (next) {
      setProductId(currentProductId ?? "");
      setError(null);
    }
  }

  function handleGenerate() {
    if (!productId) {
      setError("Choose a lender's product first");
      return;
    }
    setError(null);
    startTransition(async () => {
      try {
        await autoGenerateClientNeedsForProduct(dealId, productId);
        setOpen(false);
        toast.success("Client needs generated");
        router.refresh();
      } catch (err) {
        const message = err instanceof Error ? err.message : "Couldn't auto-generate client needs.";
        setError(message);
        toast.error(message);
      }
    });
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogTrigger asChild>
        <Button type="button" variant="outline" size="sm">
          Auto Generate
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Auto-generate client needs</DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <p className="text-sm text-muted-foreground">
            Pulls that lender&apos;s checklist for this loan type onto the deal — every lender can
            have a slightly different set (a 1003 vs. their own application, for example).
          </p>
          {products.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No lenders have a product set up for this loan category yet.
            </p>
          ) : (
            <Select value={productId} onValueChange={setProductId}>
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Choose a lender's product" />
              </SelectTrigger>
              <SelectContent>
                {products.map((p) => (
                  <SelectItem key={p.id} value={p.id}>
                    {p.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}
          {error && <p className="text-sm text-destructive">{error}</p>}
          <Button type="button" className="w-full" disabled={pending || products.length === 0} onClick={handleGenerate}>
            {pending ? "Generating…" : "Generate"}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

function AttachDocumentButton({ dealId, needId }: { dealId: string; needId: string }) {
  const router = useRouter();
  const inputRef = useRef<HTMLInputElement>(null);
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  function handleChange(e: React.ChangeEvent<HTMLInputElement>) {
    const files = e.target.files;
    if (!files || files.length === 0) return;
    setError(null);
    const formData = new FormData();
    for (const file of Array.from(files)) formData.append("file", file);
    startTransition(async () => {
      try {
        await attachDocumentToClientNeed(dealId, needId, formData);
        toast.success("Document uploaded");
        router.refresh();
      } catch (err) {
        const message = err instanceof Error ? err.message : "Couldn't upload those files.";
        setError(message);
        toast.error(message);
      } finally {
        if (inputRef.current) inputRef.current.value = "";
      }
    });
  }

  return (
    <div className="flex flex-col items-start gap-1">
      <input ref={inputRef} type="file" multiple className="hidden" onChange={handleChange} />
      <Button type="button" size="sm" variant="outline" disabled={pending} onClick={() => inputRef.current?.click()}>
        {pending ? "Uploading…" : "Attach documents"}
      </Button>
      {error && <p className="text-xs text-destructive">{error}</p>}
    </div>
  );
}

// Manual only, on purpose — never runs on its own. Reviews every document
// currently in this need; results (and the follow-up chat) are read in the
// document viewer, right next to the document they're about, not here.
function AiReviewButton({ dealId, needId }: { dealId: string; needId: string }) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();

  function handleClick() {
    startTransition(async () => {
      try {
        const result = await reviewClientNeedDocuments(dealId, needId);
        toast.success(
          result.totalFlags > 0
            ? `Reviewed — ${result.totalFlags} thing${result.totalFlags === 1 ? "" : "s"} flagged`
            : "Reviewed — nothing flagged"
        );
        if (result.errors.length) toast.error(String(result.errors[0]));
        router.refresh();
      } catch (err) {
        toast.error(err instanceof Error ? err.message : "AI review failed — try again.");
      }
    });
  }

  return (
    <Button type="button" size="sm" variant="outline" disabled={pending} onClick={handleClick}>
      <Sparkles className="size-3.5" />
      {pending ? "Reviewing…" : "AI Review"}
    </Button>
  );
}

function DocumentRow({
  document,
  onClick,
}: {
  document: ReviewableDocument;
  onClick: () => void;
}) {
  return (
    <>
      <button
        type="button"
        onClick={onClick}
        className="flex w-full items-center justify-between gap-2 rounded-md border px-3 py-2 text-left text-sm hover:bg-muted/50"
      >
        <span className="truncate">{document.fileName}</span>
        {document.reviewStatus === "approved" && <Badge variant="success">Approved</Badge>}
        {document.reviewStatus === "rejected" && <Badge variant="destructive">Rejected</Badge>}
        {document.reviewStatus === "pending" && <Badge variant="warning">Review needed</Badge>}
      </button>
      {document.rejectionNote && document.reviewStatus === "rejected" && (
        <p className="pl-3 text-xs text-muted-foreground italic">Rejected: {document.rejectionNote}</p>
      )}
    </>
  );
}

// A custom_form need's answers are one JSONB blob keyed by field name — this
// looks up each field's label from the same shared definition the borrower's
// own form was rendered from, grouped by section, so staff reviewing a
// submission see the same labels/organization the borrower saw.
function CustomFormAnswersSummary({
  customFormKey,
  data,
}: {
  customFormKey: string | null;
  data: Record<string, string>;
}) {
  const definition = getCustomFormDefinition(customFormKey);
  if (!definition) {
    return (
      <div className="rounded-md border bg-muted/30 p-3 text-sm text-muted-foreground">
        This form&apos;s definition couldn&apos;t be found — raw answers: {JSON.stringify(data)}
      </div>
    );
  }

  return (
    <div className="space-y-4 rounded-md border bg-muted/30 p-3">
      {definition.sections.map((section) => {
        const answered = section.fields.filter((f) => data[f.name]);
        if (!answered.length) return null;
        return (
          <div key={section.title} className="space-y-1">
            <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{section.title}</p>
            {answered.map((f) => {
              const raw = data[f.name];
              const display = f.options?.find((o) => o.value === raw)?.label ?? raw;
              return (
                <p key={f.name} className="text-sm">
                  <span className="text-muted-foreground">{f.label}: </span>
                  <span className="font-medium">{display}</span>
                </p>
              );
            })}
          </div>
        );
      })}
    </div>
  );
}

function RejectNeedDialog({ dealId, needId, documentIds, disabled }: { dealId: string; needId: string; documentIds: string[]; disabled: boolean }) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setError(null);
    const formData = new FormData(e.currentTarget);
    const note = String(formData.get("note") ?? "");
    startTransition(async () => {
      try {
        await rejectClientNeedDocuments(dealId, needId, documentIds, note);
        setOpen(false);
        toast.success("Need rejected");
        router.refresh();
      } catch (err) {
        const message = err instanceof Error ? err.message : "Couldn't reject these documents.";
        setError(message);
        toast.error(message);
      }
    });
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button type="button" size="sm" variant="destructive" disabled={disabled}>
          Reject Need
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Reject Need</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <Textarea name="note" rows={3} placeholder="Why are these being rejected?" required />
          {error && <p className="text-sm text-destructive">{error}</p>}
          <Button type="submit" className="w-full" variant="destructive" disabled={pending}>
            {pending ? "Rejecting…" : "Reject Need"}
          </Button>
        </form>
      </DialogContent>
    </Dialog>
  );
}

function EditNeedDialog({
  dealId,
  need,
  open,
  onOpenChange,
}: {
  dealId: string;
  need: ClientNeed;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setError(null);
    const formData = new FormData(e.currentTarget);
    startTransition(async () => {
      try {
        await updateClientNeed(dealId, need.id, formData);
        onOpenChange(false);
        toast.success("Need saved");
        router.refresh();
      } catch (err) {
        const message = err instanceof Error ? err.message : "Couldn't save that.";
        setError(message);
        toast.error(message);
      }
    });
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Edit client need</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-1.5">
            <Label htmlFor={`edit-name-${need.id}`}>Item name</Label>
            <Input id={`edit-name-${need.id}`} name="itemName" defaultValue={need.itemName} required />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor={`edit-desc-${need.id}`}>Description</Label>
            <Textarea id={`edit-desc-${need.id}`} name="description" rows={3} defaultValue={need.description ?? ""} />
          </div>
          {error && <p className="text-sm text-destructive">{error}</p>}
          <Button type="submit" className="w-full" disabled={pending}>
            {pending ? "Saving…" : "Save"}
          </Button>
        </form>
      </DialogContent>
    </Dialog>
  );
}

function HoldNeedDialog({
  dealId,
  need,
  open,
  onOpenChange,
}: {
  dealId: string;
  need: ClientNeed;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setError(null);
    const note = String(new FormData(e.currentTarget).get("note") ?? "");
    startTransition(async () => {
      try {
        await putClientNeedOnHold(dealId, need.id, note);
        onOpenChange(false);
        toast.success("Need put on hold");
        router.refresh();
      } catch (err) {
        const message = err instanceof Error ? err.message : "Couldn't put this need on hold.";
        setError(message);
        toast.error(message);
      }
    });
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Put &ldquo;{need.itemName}&rdquo; on hold</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <p className="text-sm text-muted-foreground">
            A note is required so you remember why later. While on hold, this need won&apos;t appear in reminder or
            update emails and is hidden from the borrower&apos;s upload page.
          </p>
          <Textarea name="note" rows={3} placeholder="Why is this on hold?" required />
          {error && <p className="text-sm text-destructive">{error}</p>}
          <Button type="submit" className="w-full" disabled={pending}>
            {pending ? "Saving…" : "Put on hold"}
          </Button>
        </form>
      </DialogContent>
    </Dialog>
  );
}

function NeedActionsMenu({ dealId, need }: { dealId: string; need: ClientNeed }) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [editOpen, setEditOpen] = useState(false);
  const [holdOpen, setHoldOpen] = useState(false);

  function handleResume() {
    startTransition(async () => {
      await resumeClientNeedFromHold(dealId, need.id);
      toast.success("Need resumed");
      router.refresh();
    });
  }

  function handleDelete() {
    const warning =
      need.documents.length > 0
        ? `Delete "${need.itemName}"? This also deletes the ${need.documents.length} document(s) uploaded against it. This can't be undone.`
        : `Delete "${need.itemName}"? This can't be undone.`;
    if (!window.confirm(warning)) return;
    startTransition(async () => {
      await deleteClientNeedFromDeal(dealId, need.id);
      router.refresh();
    });
  }

  return (
    <>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button type="button" variant="ghost" size="icon-sm" disabled={pending}>
            <MoreVertical className="size-4" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuItem onClick={() => setEditOpen(true)}>Edit</DropdownMenuItem>
          {need.onHoldAt ? (
            <DropdownMenuItem onClick={handleResume}>Resume (take off hold)</DropdownMenuItem>
          ) : need.status !== "accepted" ? (
            <DropdownMenuItem onClick={() => setHoldOpen(true)}>Put on hold</DropdownMenuItem>
          ) : null}
          <DropdownMenuItem variant="destructive" onClick={handleDelete}>
            Delete
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
      <EditNeedDialog dealId={dealId} need={need} open={editOpen} onOpenChange={setEditOpen} />
      <HoldNeedDialog dealId={dealId} need={need} open={holdOpen} onOpenChange={setHoldOpen} />
    </>
  );
}

function ClientNeedRow({
  dealId,
  need,
  selected,
  onToggleSelected,
}: {
  dealId: string;
  need: ClientNeed;
  selected: boolean;
  onToggleSelected: (checked: boolean) => void;
}) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [reviewOpen, setReviewOpen] = useState(false);
  const [reviewDocId, setReviewDocId] = useState<string | null>(null);
  const [expanded, setExpanded] = useState(false);

  function runAction(action: () => Promise<void>) {
    startTransition(async () => {
      await action();
      router.refresh();
    });
  }

  function openReview(docId: string) {
    setReviewDocId(docId);
    setReviewOpen(true);
  }

  const pendingIds = need.documents.filter((d) => d.reviewStatus === "pending").map((d) => d.id);
  const nonRejectedIds = need.documents.filter((d) => d.reviewStatus !== "rejected").map((d) => d.id);
  const hasDocuments =
    (need.needType === "document_upload" || need.needType === "pandadoc_form") && need.documents.length > 0;
  const hasAnswers = need.needType === "questionnaire" && need.answers.some((a) => a.answerText);
  const hasCustomFormData = need.needType === "custom_form" && Boolean(need.customFormData);
  const hasExpandableContent = hasDocuments || hasAnswers || hasCustomFormData;
  const aiFlagCount = need.documents.reduce((sum, d) => sum + (d.aiReviewFlags?.flags.length ?? 0), 0);

  function handleNameClick() {
    if (hasDocuments) openReview(pendingIds[0] ?? need.documents[0].id);
    else setExpanded((v) => !v);
  }

  return (
    <Card>
      <CardContent className="space-y-3 py-4">
        <div className="flex items-start justify-between gap-4">
          <div className="flex items-start gap-3">
            <Checkbox
              checked={selected}
              onCheckedChange={(v) => onToggleSelected(v === true)}
              className="mt-0.5"
            />
            <div>
            <p className="flex items-center gap-2 text-sm font-medium">
              {hasExpandableContent ? (
                <button
                  type="button"
                  onClick={handleNameClick}
                  className="hover:underline"
                  title={hasDocuments ? "Open the document viewer to review all at once" : "Show the submitted answers"}
                >
                  {need.itemName}
                </button>
              ) : (
                need.itemName
              )}
              {hasExpandableContent ? (
                <button
                  type="button"
                  onClick={() => setExpanded((v) => !v)}
                  className="inline-flex items-center gap-0.5"
                  title={expanded ? "Hide details" : "Show details"}
                >
                  <Badge variant={STATUS_VARIANT[need.status]}>{STATUS_LABEL[need.status]}</Badge>
                  {expanded ? (
                    <ChevronDown className="size-3.5 text-muted-foreground" />
                  ) : (
                    <ChevronRight className="size-3.5 text-muted-foreground" />
                  )}
                </button>
              ) : (
                <Badge variant={STATUS_VARIANT[need.status]}>{STATUS_LABEL[need.status]}</Badge>
              )}
              {need.onHoldAt && <Badge variant="outline">On Hold</Badge>}
              {aiFlagCount > 0 && (
                <Badge variant="warning" title="Flagged by AI review — open the document viewer to see why">
                  <Sparkles className="size-3" />
                  {aiFlagCount} flagged
                </Badge>
              )}
              {need.needType !== "document_upload" && (
                <span className="text-xs text-muted-foreground">
                  (
                  {need.needType === "esign"
                    ? "e-sign"
                    : need.needType === "link"
                      ? "link"
                      : need.needType === "pandadoc_form"
                        ? "PandaDoc"
                        : need.needType === "custom_form"
                          ? "application"
                          : "questionnaire"}
                  )
                </span>
              )}
            </p>
            {need.onHoldAt && (
              <p className="text-xs text-amber-600">
                On hold since {need.onHoldAt.toLocaleDateString()}: {need.onHoldNote}
              </p>
            )}
            {need.description && <p className="text-sm text-muted-foreground">{need.description}</p>}
            {need.needType === "document_upload" && need.minFiles > 1 && (
              <p className="text-xs text-amber-600">Requires {need.minFiles} files (e.g. front &amp; back) before it can be accepted</p>
            )}
            {need.needType === "document_upload" && need.templateFileName && (
              <a
                href={`/api/deal-client-needs/${need.id}/template-file`}
                target="_blank"
                rel="noreferrer"
                className="text-xs text-muted-foreground underline"
              >
                Download template: {need.templateFileName}
              </a>
            )}
            {need.needType === "link" && need.linkUrl && (
              <a
                href={need.linkUrl}
                target="_blank"
                rel="noreferrer"
                className="text-xs text-muted-foreground underline"
              >
                Open link
              </a>
            )}
            {need.needType === "pandadoc_form" && (
              <p className="text-xs text-muted-foreground">
                {need.pandadocDocumentId
                  ? `Sent via PandaDoc${need.sentAt ? ` on ${need.sentAt.toLocaleDateString()}` : ""}`
                  : "Not sent yet — click Send to Borrower to create and send this form"}
              </p>
            )}
            </div>
          </div>
          <div className="flex shrink-0 items-center gap-2">
            {need.needType === "document_upload" || need.needType === "pandadoc_form" ? (
              <>
                {need.needType === "document_upload" && <AttachDocumentButton dealId={dealId} needId={need.id} />}
                {need.documents.length > 0 && <AiReviewButton dealId={dealId} needId={need.id} />}
                {pendingIds.length > 0 && (
                  <Button
                    type="button"
                    size="sm"
                    variant="success"
                    disabled={pending}
                    onClick={() => runAction(() => approveClientNeedDocuments(dealId, need.id, pendingIds))}
                  >
                    Accept Need
                  </Button>
                )}
                {nonRejectedIds.length > 0 && (
                  <RejectNeedDialog dealId={dealId} needId={need.id} documentIds={nonRejectedIds} disabled={pending} />
                )}
              </>
            ) : need.status !== "accepted" ? (
              <Button
                type="button"
                size="sm"
                variant="secondary"
                disabled={pending}
                onClick={() => runAction(() => markNonDocumentNeedAccepted(dealId, need.id))}
              >
                Mark Accepted
              </Button>
            ) : (
              <Button
                type="button"
                size="sm"
                variant="ghost"
                disabled={pending}
                onClick={() => runAction(() => reopenNonDocumentNeed(dealId, need.id))}
              >
                Reopen
              </Button>
            )}
            <NeedActionsMenu dealId={dealId} need={need} />
          </div>
        </div>

        {hasDocuments && expanded && (
          <div className="space-y-1">
            {need.documents.map((doc) => (
              <DocumentRow key={doc.id} document={doc} onClick={() => openReview(doc.id)} />
            ))}
          </div>
        )}

        {hasAnswers && expanded && (
          <div className="space-y-1.5 rounded-md border bg-muted/30 p-3">
            {need.answers
              .filter((a) => a.answerText)
              .map((a) => (
                <p key={a.id} className="text-sm">
                  <span className="text-muted-foreground">{a.questionText}: </span>
                  <span className="font-medium">{a.answerText}</span>
                </p>
              ))}
          </div>
        )}

        {hasCustomFormData && expanded && need.customFormData && (
          <CustomFormAnswersSummary customFormKey={need.customFormKey} data={need.customFormData} />
        )}
      </CardContent>

      {reviewDocId && (
        <ClientNeedDocumentReviewDialog
          dealId={dealId}
          needId={need.id}
          needName={need.itemName}
          documents={need.documents}
          initialDocumentId={reviewDocId}
          open={reviewOpen}
          onOpenChange={setReviewOpen}
        />
      )}
    </Card>
  );
}

// One combined send flow: opens to a loading state, fetches the rendered
// subject/body (rejected items first, then still-outstanding ones below —
// this is the only client-needs email now, whether it's the very first send
// or a follow-up after a rejection), lets the processor edit the wording,
// then sends exactly what's on screen.
function SendToBorrowerDialog({
  dealId,
  selectedNeeds,
  hasBorrowerEmail,
  triggerClassName,
}: {
  dealId: string;
  selectedNeeds: ClientNeed[];
  hasBorrowerEmail: boolean;
  triggerClassName?: string;
}) {
  const router = useRouter();
  const bodyRef = useRef<HTMLDivElement>(null);
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [subject, setSubject] = useState("");
  const [body, setBody] = useState("");
  const [to, setTo] = useState("");
  const [cc, setCc] = useState("");
  const [signatureHtml, setSignatureHtml] = useState("");
  const [candidates, setCandidates] = useState<RecipientCandidate[]>([]);

  const rejectedCount = selectedNeeds.filter((n) => n.documents.some((d) => d.reviewStatus === "rejected")).length;

  function handleOpenChange(next: boolean) {
    setOpen(next);
    if (!next || !hasBorrowerEmail) return;
    setError(null);
    setLoading(true);
    const needIds = selectedNeeds.map((n) => n.id);
    startTransition(async () => {
      try {
        const preview = await previewClientNeedsUpdateEmail(dealId, needIds);
        setSubject(preview.subject);
        setBody(preview.body);
        setTo(preview.to);
        setCc(preview.cc);
        setSignatureHtml(preview.signatureHtml);
        setCandidates(preview.candidates);
      } catch (err) {
        const message = err instanceof Error ? err.message : "Couldn't build this email.";
        setError(message);
        toast.error(message);
      } finally {
        setLoading(false);
      }
    });
  }

  function handleSend() {
    setError(null);
    const needIds = selectedNeeds.map((n) => n.id);
    const finalBody = bodyRef.current?.innerHTML ?? body;
    startTransition(async () => {
      try {
        await sendClientNeedsUpdateEmail(dealId, needIds, to, cc, subject, finalBody);
        setOpen(false);
        toast.success("Email sent to borrower");
        router.refresh();
      } catch (err) {
        const message = err instanceof Error ? err.message : "Couldn't send this email.";
        setError(message);
        toast.error(message);
      }
    });
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogTrigger asChild>
        <Button type="button" size="sm" disabled={selectedNeeds.length === 0} className={triggerClassName}>
          Send to Borrower ({selectedNeeds.length})
        </Button>
      </DialogTrigger>
      <DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-4xl">
        <DialogHeader>
          <DialogTitle>
            {rejectedCount > 0 ? "Send update — includes rejected items" : "Send client needs to borrower"}
          </DialogTitle>
        </DialogHeader>
        {!hasBorrowerEmail ? (
          <p className="text-sm text-muted-foreground">Add a borrower email on the Overview tab first.</p>
        ) : loading ? (
          <p className="text-sm text-muted-foreground">Building preview…</p>
        ) : error && !subject ? (
          <p className="text-sm text-destructive">{error}</p>
        ) : (
          <div className="space-y-3">
            <div className="grid grid-cols-2 gap-3">
              <RecipientLine id="send-to" label="To" value={to} onChange={setTo} candidates={candidates} />
              <RecipientLine id="send-cc" label="Cc" value={cc} onChange={setCc} candidates={candidates} />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="send-subject">Subject</Label>
              <Input id="send-subject" value={subject} onChange={(e) => setSubject(e.target.value)} />
            </div>
            <div className="space-y-1.5">
              <Label>Email preview — click any text below to edit it</Label>
              <HtmlBodyEditor html={body} bodyRef={bodyRef} />
            </div>
            <SignaturePreview html={signatureHtml} />
            {error && <p className="text-sm text-destructive">{error}</p>}
            <Button type="button" className="w-full" disabled={pending} onClick={handleSend}>
              {pending ? "Sending…" : "Send email"}
            </Button>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}

function ReminderSettingsDialog({
  dealId,
  remindersPaused,
  reminderIntervalHours,
  open,
  onOpenChange,
}: {
  dealId: string;
  remindersPaused: boolean;
  reminderIntervalHours: number;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [interval, setInterval] = useState(String(reminderIntervalHours));
  const [paused, setPaused] = useState(remindersPaused);

  function handleOpenChange(next: boolean) {
    onOpenChange(next);
    if (next) {
      setInterval(String(reminderIntervalHours));
      setPaused(remindersPaused);
    }
  }

  function handleSave() {
    startTransition(async () => {
      await updateClientNeedsReminderSettings(dealId, Number(interval), paused);
      onOpenChange(false);
      router.refresh();
    });
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Client needs reminder settings</DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <p className="text-xs text-muted-foreground">
            Once automated reminders are turned on, the borrower will get a re-send of the same
            update email (rejected items, then outstanding ones) on this schedule until everything
            is accepted.
          </p>
          <div className="space-y-2">
            <Label>Send a reminder every</Label>
            <RadioGroup value={interval} onValueChange={setInterval} disabled={paused}>
              {REMINDER_INTERVAL_OPTIONS.map((opt) => (
                <label key={opt.hours} className="flex items-center gap-2 text-sm">
                  <RadioGroupItem value={String(opt.hours)} />
                  {opt.label}
                </label>
              ))}
            </RadioGroup>
          </div>
          <div className="flex items-center justify-between border-t pt-4">
            <div>
              <p className="text-sm font-medium">Pause all reminders</p>
              <p className="text-xs text-muted-foreground">Stops reminders for this deal entirely.</p>
            </div>
            <Button
              type="button"
              size="sm"
              variant={paused ? "default" : "outline"}
              onClick={() => setPaused((p) => !p)}
            >
              {paused ? "Paused" : "Pause reminders"}
            </Button>
          </div>
          <Button type="button" className="w-full" disabled={pending} onClick={handleSave}>
            {pending ? "Saving…" : "Save"}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

const REMINDER_INTERVAL_OPTIONS = CLIENT_NEEDS_REMINDER_INTERVAL_HOURS.map((hours) => ({
  hours,
  label: hours === 24 ? "24 hours (default)" : hours === 168 ? "Once a week" : `${hours} hours`,
}));

// The caret half of the Send to Borrower split button — everything about
// the reminder schedule lives here since it's the thing you'd naturally
// reach for right after sending, without needing its own toolbar slot.
function ReminderMenu({
  dealId,
  remindersPaused,
  reminderIntervalHours,
}: {
  dealId: string;
  remindersPaused: boolean;
  reminderIntervalHours: number;
}) {
  const router = useRouter();
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [pending, startTransition] = useTransition();

  function togglePaused() {
    startTransition(async () => {
      await updateClientNeedsReminderSettings(dealId, reminderIntervalHours, !remindersPaused);
      toast.success(remindersPaused ? "Reminders resumed" : "Reminders paused");
      router.refresh();
    });
  }

  return (
    <>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button
            type="button"
            size="sm"
            className="rounded-l-none border-l border-l-primary-foreground/20 px-2"
            aria-label="Reminder options"
          >
            <ChevronDown className="size-3.5" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuItem onClick={() => setSettingsOpen(true)}>
            Reminder settings{remindersPaused ? " (Paused)" : ""}
          </DropdownMenuItem>
          <DropdownMenuItem disabled={pending} onClick={togglePaused}>
            {remindersPaused ? "Resume reminders" : "Pause reminders"}
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
      <ReminderSettingsDialog
        dealId={dealId}
        remindersPaused={remindersPaused}
        reminderIntervalHours={reminderIntervalHours}
        open={settingsOpen}
        onOpenChange={setSettingsOpen}
      />
    </>
  );
}

// The overflow menu for setup/utility actions that aren't part of the core
// send workflow — used far less often than Auto Generate or Send to Borrower.
function MoreActionsMenu({
  dealId,
  catalog,
  allProducts,
  needs,
}: {
  dealId: string;
  catalog: DealCatalogItem[];
  allProducts: { id: string; label: string }[];
  needs: ClientNeed[];
}) {
  const router = useRouter();
  const [addNeedOpen, setAddNeedOpen] = useState(false);
  const [reviewingAll, startReviewAllTransition] = useTransition();
  const hasAnyDocuments = needs.some((n) => n.documents.length > 0);

  function handleReviewAll() {
    startReviewAllTransition(async () => {
      try {
        const result = await reviewAllClientNeedDocumentsForDeal(dealId);
        toast.success(
          result.totalFlags > 0
            ? `Reviewed ${result.reviewed} document${result.reviewed === 1 ? "" : "s"} — ${result.totalFlags} thing${result.totalFlags === 1 ? "" : "s"} flagged`
            : `Reviewed ${result.reviewed} document${result.reviewed === 1 ? "" : "s"} — nothing flagged`
        );
        router.refresh();
      } catch (err) {
        toast.error(err instanceof Error ? err.message : "AI review failed — try again.");
      }
    });
  }

  return (
    <>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button type="button" size="icon-sm" variant="outline" aria-label="More actions">
            <MoreVertical className="size-4" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuItem onClick={() => setAddNeedOpen(true)}>+ Add client need</DropdownMenuItem>
          <CopyClientNeedsButton items={needs.filter((n) => n.status !== "accepted").map((n) => n.itemName)} />
          <CopyUploadLinkItem dealId={dealId} />
          <DropdownMenuItem disabled={reviewingAll || !hasAnyDocuments} onClick={handleReviewAll}>
            <Sparkles className="size-4" />
            {reviewingAll ? "Reviewing all…" : "AI Review all documents"}
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
      <AddClientNeedToDealDialog
        dealId={dealId}
        catalog={catalog}
        allProducts={allProducts}
        open={addNeedOpen}
        onOpenChange={setAddNeedOpen}
      />
    </>
  );
}

export function ClientNeedsTab({
  dealId,
  needs,
  loanCategoryProducts,
  allProducts,
  currentProductId,
  hasBorrowerEmail,
  remindersPaused,
  reminderIntervalHours,
  hasAcceptedProduct,
  catalog,
}: {
  dealId: string;
  needs: ClientNeed[];
  loanCategoryProducts: { id: string; label: string }[];
  allProducts: { id: string; label: string }[];
  currentProductId: string | null;
  hasBorrowerEmail: boolean;
  remindersPaused: boolean;
  reminderIntervalHours: number;
  hasAcceptedProduct: boolean;
  catalog: DealCatalogItem[];
}) {
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [activeTab, setActiveTab] = useState<"docs" | "esign">("docs");

  const docsNeeds = needs.filter((n) => !ESIGN_NEED_TYPES.has(n.needType));
  const esignNeeds = needs.filter((n) => ESIGN_NEED_TYPES.has(n.needType));
  const visibleNeeds = activeTab === "docs" ? docsNeeds : esignNeeds;

  const selectedNeeds = needs.filter((n) => selectedIds.has(n.id) && !n.onHoldAt);
  // "Select all" only ever touches the tab you're looking at — flipping to
  // the other tab shouldn't silently grab (or drop) items you can't see.
  const allVisibleSelected = visibleNeeds.length > 0 && visibleNeeds.every((n) => selectedIds.has(n.id));

  function toggleAll(checked: boolean) {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      for (const n of visibleNeeds) {
        if (checked) next.add(n.id);
        else next.delete(n.id);
      }
      return next;
    });
  }

  function toggleOne(id: string, checked: boolean) {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (checked) next.add(id);
      else next.delete(id);
      return next;
    });
  }

  return (
    <div className="space-y-4">
      {!hasAcceptedProduct && (
        <p className="text-sm text-muted-foreground">
          Client needs auto-populate once a term sheet is accepted, or click Auto Generate below
          to pull in a specific lender&apos;s checklist for this loan type right now. You can also
          add items manually.
        </p>
      )}

      <div className="flex flex-wrap items-center justify-between gap-2">
        <label className="flex items-center gap-2 text-sm">
          <Checkbox
            checked={allVisibleSelected}
            onCheckedChange={(v) => toggleAll(v === true)}
            disabled={visibleNeeds.length === 0}
          />
          Select all
        </label>
        <div className="flex flex-wrap gap-2">
          <AutoGenerateDialog dealId={dealId} products={loanCategoryProducts} currentProductId={currentProductId} />
          <div className="inline-flex">
            <SendToBorrowerDialog
              dealId={dealId}
              selectedNeeds={selectedNeeds}
              hasBorrowerEmail={hasBorrowerEmail}
              triggerClassName="rounded-r-none"
            />
            <ReminderMenu
              dealId={dealId}
              remindersPaused={remindersPaused}
              reminderIntervalHours={reminderIntervalHours}
            />
          </div>
          <MoreActionsMenu dealId={dealId} catalog={catalog} allProducts={allProducts} needs={needs} />
        </div>
      </div>

      <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as "docs" | "esign")}>
        <TabsList>
          <TabsTrigger value="docs">Docs &amp; Forms ({docsNeeds.length})</TabsTrigger>
          <TabsTrigger value="esign">E-sign ({esignNeeds.length})</TabsTrigger>
        </TabsList>

        <TabsContent value="docs" className="space-y-2 pt-2">
          {docsNeeds.map((need) => (
            <ClientNeedRow
              key={need.id}
              dealId={dealId}
              need={need}
              selected={selectedIds.has(need.id)}
              onToggleSelected={(checked) => toggleOne(need.id, checked)}
            />
          ))}
          {docsNeeds.length === 0 && <p className="text-sm text-muted-foreground">No docs or forms yet.</p>}
        </TabsContent>

        <TabsContent value="esign" className="space-y-2 pt-2">
          {esignNeeds.map((need) => (
            <ClientNeedRow
              key={need.id}
              dealId={dealId}
              need={need}
              selected={selectedIds.has(need.id)}
              onToggleSelected={(checked) => toggleOne(need.id, checked)}
            />
          ))}
          {esignNeeds.length === 0 && <p className="text-sm text-muted-foreground">No e-sign tasks yet.</p>}
        </TabsContent>
      </Tabs>
    </div>
  );
}
